name: rummikubsolver
version: 1.1.0.0
github: "gregorias/rummikubsolver"
license: GPL-3
license-file: LICENSE
author: "Grzegorz Milka"
maintainer: "grzegorzmilka@gmail.com"
copyright: "2020-2023 Grzegorz Milka"

extra-source-files:
  - README.md

# Metadata used when publishing your package
synopsis: An interactive solver for Rummikub with a web interface.
category: Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/gregorias/findata-transcoder#readme>

dependencies:
  - base >= 4.14 && < 5

language: GHC2021

default-extensions:
  - DataKinds
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedLabels
  - OverloadedRecordDot
  - OverloadedStrings
  - QuasiQuotes
  - TypeFamilies
  - TypeOperators

# no-type-defaults, this is dangerous, but in terms of convenience it's so
# useful to use ExtendedDefaultRules that I keep it.
ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Wmissing-deriving-strategies
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-type-defaults
  - -Wno-partial-type-signatures
  - -Wno-name-shadowing

library:
  source-dirs: src
  dependencies:
    - array
    - closed
    - containers
    - extra
    - glpk-hs
    - megaparsec
    - mtl
    - relude
    - safe
    - optparse-applicative
    - text
    - transformers
    - threepenny-gui

executables:
  rummikubsolver:
    main: Main.hs
    source-dirs: executables
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - mtl
      - relude
      - rummikubsolver
      - safe

tests:
  test-rummikubsolver:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Main
    dependencies:
      - closed
      - hspec
      - hspec-contrib
      - hspec-expectations-pretty-diff
      - HUnit
      - relude
      - rummikubsolver
